### ISSUE TITLE
DNA-C now requiring HTTPS

### ISSUE THREAD

**Issue by MrGudgeon** [robertcsapo/cisco-dnac-platform-webex-notifications#2]
When putting the Endpoint information, you get a successful connection when using http://

When clicking "activate", DNA-C says that it must be an HTTPS connection. When changing the endpoint to https://, you get a "Unrecognized SSL message, plaintext connection?" message.

I am on version 1.3.0.3 of DNA Center.

**Comment by robertcsapo** [comment]
@MrGudgeon If you try with a webhook from https://webhook.site, does it work?

I've just tried with Cisco DNA Center 1.3.0.4 and it was successful. (Didn't try with **http://**)
_(Cisco DNA Center screenshot)_
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/11992244/64711011-400ad200-d4b9-11e9-9a42-fb71ff081246.png">

This is what webhook.site displays
_(webhook.site screenshot)_
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/11992244/64711121-6e88ad00-d4b9-11e9-825b-c24f738a6a12.png">

**Comment by MrGudgeon** [comment]
@robertcsapo That worked successfully. I might be looking at this wrong, but this is what I have done.
On a centos box with docker (ip address 10.1.1.1), I installed your docker container on it. In DNA, for REST End Point, I put http://10.1.1.1:5000/dnac
With this, it will successfully connect with the test, but DNA won't let me Save it because it isn't an https URL to the location machine running the docker container. But when I move it to https://10.1.1.1:5000/dnac, DNAC gets an SSL error message. I wasn't sure if this would be an issue with the CentOS box itself or maybe the container?


![Screen Shot 2019-09-11 at 12 32 04 PM](https://user-images.githubusercontent.com/18078872/64720475-2e610480-d490-11e9-83e6-58a6ab6b6694.png)


![Screen Shot 2019-09-11 at 12 31 18 PM](https://user-images.githubusercontent.com/18078872/64720497-34ef7c00-d490-11e9-95fa-3314c8f69553.png)



Please let me know if I need to explain anything further. Thanks!

**Comment by robertcsapo** [comment]
@MrGudgeon Got it!
You want to run Cisco DNA Center directly to the Flask Service (which hasn't SSL enabled).

Could you try this test build with adhoc SSL enabled and see if it works for you?
```docker run -it --rm -p 5000:5000 -e WEBEX_TEAMS_ACCESS_TOKEN="TOKEN" -e WEBEX_TEAMS_ROOM_ID="ID" robertcsapo/cisco-dnac-platform-webex-notifications:ssl-test```

Then use **https** at _"Rest Endpoint"_ in Cisco DNA Center.

**Comment by MrGudgeon** [comment]
@robertcsapo That got it connecting! Except now DNA Center has changed how they do things in Version 1.3.1.0 (which i just upgraded to). You no longer schedule when it pushes the events to your endpoint, rather it will send the notification out once the event has occurred.

Now, the Network Events for REST API Endpoint exists in the GUI still, but has now been depreciated.
You now have to go to Platform > Developer Toolkit > Events. Select one of the events and click on Subscribe.

From here, you have multiple options to configure. You can now select a type, REST or Email.
If you choose REST, you get these options:
URL
Trust Certificate (Yes or No)
HTTP Method - (POST or PUT)
Authentication - (Basic, Token, No Auth). If you choose an authentication method, it fills out one of the headers with either "Authorization" for basic, or "X-Auth-Token" for Token.
Headers - (you can put the Header Key and Header Value). It also gives the option to add more Headers.

My question is, with these options, is there a way to still connect this to your docker image? I have been messing with the Webex Teams API docs and with the options DNA Center gives you to fill out, I have been unable to see how to put the room ID in the GUI as there isn't a "body" option.

Thank you for your help!

**Comment by robertcsapo** [comment]
@MrGudgeon I haven’t had the chance to verify this service with Cisco DNA Center 1.3.1.
But based on your input, you shouldn’t need to add any Webex Room ID in the GUI (webhook headers)

You specify the Cisco Webex Token and Room ID, when you’re running the service.

```
docker run -d -p 5000:5000 \
-e WEBEX_TEAMS_ACCESS_TOKEN="TOKEN" \
-e WEBEX_TEAMS_ROOM_ID="ID" \
robertcsapo/cisco-dnac-platform-webex-notifications:ssl-test
```

Any incoming JSON Payload (based on the format for Cisco DNA Center) will be sent tot that Webex Room ID that you put as **WEBEX_TEAMS_ROOM_ID** environment.

**Comment by robertcsapo** [comment]
@MrGudgeon I've got a test build for Cisco DNA Center 1.3.1 (with ssl as option)
(note that ```--ssl``` is now an argument instead)
```
docker run -d -p 5000:5000 \
-e WEBEX_TEAMS_ACCESS_TOKEN="TOKEN" \
-e WEBEX_TEAMS_ROOM_ID="ID" \
robertcsapo/cisco-dnac-platform-webex-notifications:1.3.1 --ssl
```

As for settings in Cisco DNA Center.
Go to **System** -> **System Settings**
**Settings** -> **Events and Subscription**

Mark all the events you want (make sure ~53 events i marked, if you want all of them)
Click on **Subscribe** add all the details for your Service

In case you need to edit. Click on any Event Name and switch to tab **Active Subscriptions**
There you have options like **edit** or **unsubscribe**

_(Guide for Cisco DNA Center 1.3.1+ Events)_
